### ISSUE TITLE
Error: While importing 'wsgi', an ImportError was raised:

### ISSUE THREAD

**Issue by keirosang** [patw/Bottybot#1]
`PS F:\ao\llama\Bottybot> .\bottybot.bat
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'wsgi', an ImportError was raised:

Traceback (most recent call last):
  File "C:\Users\luoqi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\cli.py", line 247, in locate_app
    __import__(module_name)
  File "F:\ao\llama\Bottybot\wsgi.py", line 4, in <module>
    from app import app
  File "F:\ao\llama\Bottybot\app.py", line 25, in <module>
    from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai' (C:\Users\luoqi\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\__init__.py)`

**Comment by patw** [comment]
Try running "pip install -r requirements.txt" again.  The code was updated on Friday to allow it to run against OpenAI and Mistral.ai.  If you have API keys for either of these services, check out the env.sample file to see how to configure them.

**Comment by patw** [comment]
I just added some code to allow one or both of the keys to be missing from the .env file, so you should be able to run without having an OpenAI or Mistral.ai account.  Maybe later I'll hide the drop down entirely if it's not running in multi model mode or maybe allow multiple configured llama.cpp server mode models.  I run about 5 different ones here, that would actually be useful.
